### ISSUE TITLE
ILLEGAL MEEPLE PLACEMENT causing a team to make 2 moves

### ISSUE THREAD

**Issue by Martakia** [chausen/TigerZoneServer#6] opened 2016-12-03 23:57 UTC
With permission from Dr. Small, I am posting a bug that I worked with the server team to solve Friday morning at 4am.

**Bug**
The bug consisted of an ILLEGAL MEEPLE PLACEMENT happening by the enemy team in GAME 2. This would then cause them to forfeit the game 2 and they would then receive their message to play their move in game 1. From my perspective we were then told that we forfeited due to an illegal message, but we never received a "MAKE YOUR MOVE" message from the server, so we would have never sent a message that was illegal. 

After investigating into the enemy team's log file, it was found that the server would send them their move and they would send their response. They would then receive OUR move and respond with an illegal message due to the wrong move number. This would trigger the server to believe the message was from us and because it would identify that it had received an illegal move, forfeit TEAMR, when it was in fact telling TEAMP to make 2 moves without incrementing the move number properly. 

**EDIT** Forgot to mention this only occured when ILLEGAL MEEPLE PLACEMENT happened in game 2, but not game 1.

[LogInfo - illega message forfeit by illegal meeple placement.txt](https://github.com/chausen/TigerZoneServer/files/629198/LogInfo.-.illega.message.forfeit.by.illegal.meeple.placement.txt)
**Snippet specific to bug**
2016-12-02 03:25:38.992 | SENDING: GAME 1 MOVE 73 PLACE JLLL- AT 2 6 0 NONE
2016-12-02 03:25:39.003 | Recieving Response: GAME 1 MOVE 73 PLAYER TEAMR PLACED JLLL- AT 2 6 0 NONE
2016-12-02 03:25:39.081 | Recieving Response: GAME 2 MOVE 73 PLAYER TEAMW FORFEITED: INVALID MEEPLE PLACEMENT
2016-12-02 03:25:39.081 | Recieving Response: GAME 1 MOVE 74 PLAYER TEAMW PLACED TLTJD AT -5 0 270 TIGER 8
2016-12-02 03:25:39.134 | Recieving Response: GAME 1 MOVE 75 PLAYER TEAMR FORFEITED: ILLEGAL MESSAGE RECEIVED 
2016-12-02 03:25:39.134 | Recieving Response: GAME 1 OVER PLAYER TEAMR WIN PLAYER TEAMW FORFEITED
2016-12-02 03:25:39.135 | Recieving Response: GAME 2 OVER PLAYER TEAMW FORFEITED PLAYER TEAMR WIN
2016-12-02 03:25:39.135 | Recieving Response: END OF ROUND 1 OF 1

**Log from opponent - TEAMP (entered test as TEAMW)**
[2016_12_02-03_23_26.txt](https://github.com/chausen/TigerZoneServer/files/629200/2016_12_02-03_23_26.txt)
**Snippet specific to bug**
Server: GAME 1 MOVE 73 PLAYER TEAMR PLACED JLLL- AT 2 6 0 NONE
Server: GAME 2 MOVE 73 PLAYER TEAMW FORFEITED: INVALID MEEPLE PLACEMENT
Server: MAKE YOUR MOVE IN GAME 1 WITHIN 1 SECOND: MOVE 74 PLACE TLTJD
Client: GAME 1 MOVE 74 PLACE TLTJD AT -5 0 270 TIGER 8
Server: GAME 1 MOVE 74 PLAYER TEAMW PLACED TLTJD AT -5 0 270 TIGER 8
Server: MAKE YOUR MOVE IN GAME 1 WITHIN 1 SECOND: MOVE 74 PLACE JLLJ-
Client: GAME 1 MOVE 74 PLACE JLLJ- AT 1 4 180 TIGER 2
Server: GAME 1 MOVE 75 PLAYER TEAMR FORFEITED: ILLEGAL MESSAGE RECEIVED 
Server: GAME 1 OVER PLAYER TEAMR WIN PLAYER TEAMW FORFEITED

**Solution**
It was found that there was a bracket missing in some of the logic and when that was fixed, the bug has since been resolved.

**Comment by chausen** [comment] 2016-12-05 00:10
Thank you for posting. Since the issue is resolved, I will go ahead and close it.

**Closed by chausen** 2016-12-05 00:10 UTC
